version: '3.9'

services:
  # envoy:
  #   image: envoyproxy/envoy:v1.25-latest
  #   ports:
  #     - "8080:8080"
  #   sysctls:
  #     net.core.somaxconn: 65535
  #     net.ipv4.ip_local_port_range: "1024 65535"
  #   volumes:
  #     - ./envoy.yaml:/etc/envoy/envoy.yaml
  #   depends_on:
  #     - worker1

  #   networks:
  #     - mynetwork
  worker1:
    build:
      context: ./src/implementation1
    env_file:
      - ./src/.env
    command: ["node", "index.js"]
    environment:
      - PORT=3001
    networks:
    - mynetwork

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  k6_1:
    image: loadimpact/k6:latest
    container_name: k6_runner1
    platform: linux/amd64
    depends_on:
      - worker1
      - postgres
    volumes:
      - ./test/loadtest1.js:/loadtest1.js:ro
    command: run /loadtest1.js
    networks:
      - mynetwork


volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
